function onCreate()
	addHaxeLibrary("GameOverSubstate")
	addHaxeLibrary("Math")
	addHaxeLibrary("FlxG", 'flixel')
	addHaxeLibrary("FlxBar", "flixel.ui")
    addHaxeLibrary('FlxMath', 'flixel.math')
	addHaxeLibrary('FlxTween', 'flixel.tweens')
	addHaxeLibrary("FlxColor", 'flixel.util')
	addHaxeLibrary("FlxStringUtil", "flixel.util")
	addHaxeLibrary("FlxEase", 'flixel.tweens')
	addHaxeLibrary("FlxRuntimeShader", "flixel.addons.display")
	addHaxeLibrary("ShaderFilter", "openfl.filters")
	addHaxeLibrary("Std")
	addHaxeLibrary("Paths")
	addHaxeLibrary('Type')
	addHaxeLibrary('Application', 'lime.app')
	addHaxeLibrary('Image', 'lime.graphics')
	addHaxeLibrary('WindowData', 'lime.tools')
	addHaxeLibrary('System', 'openfl.system')
	addHaxeLibrary('Lib', 'openfl')
	addHaxeLibrary("Sys")
	addHaxeLibrary("VideoSprite", "objects")
	addHaxeLibrary("FlxVideo", "hxcodec.flixel")
	addHaxeLibrary('FlxTypeText', 'flixel.addons.text')
	if stringStartsWith(version, '0.6') then
        addHaxeLibrary("GameOverSubstate")
        addHaxeLibrary('Character')
		addHaxeLibrary('HealthIcon')
		addHaxeLibrary("Boyfriend")
		addHaxeLibrary("VideoHandler", "hxcodec")
		addHaxeLibrary("VideoSprite", "hxcodec")
		addHaxeLibrary("AttachedSprite")
    else
		addHaxeLibrary("PauseSubState", 'substates')
        addHaxeLibrary("GameOverSubstate", 'substates')
        addHaxeLibrary('Character', 'objects')
		addHaxeLibrary('HealthIcon', 'objects')
		addHaxeLibrary("Boyfriend", "objects")
		addHaxeLibrary('Bar', 'objects')
		addHaxeLibrary("FlxVideoSprite", "hxcodec.flixel")
		addHaxeLibrary("FlxVideo", "hxcodec.flixel")
		addHaxeLibrary("Paths", "backend")
		addHaxeLibrary("AttachedSprite", "objects")
		addHaxeLibrary("Mods", "backend")
		addHaxeLibrary("FlxFlicker", "flixel.effects")
		addHaxeLibrary("WeekData", "backend")
    end
end